### ISSUE TITLE
holy-project-0.2.0.1 build failure with http-conduit-2.3

### ISSUE THREAD

**Issue by DanBurton** [yogsototh/holy-project#7]
As seen on the Stackage build server:

```
[2 of 7] Compiling HolyProject.GithubAPI ( src/HolyProject/GithubAPI.hs, dist/build/holy-project/holy-project-tmp/HolyProject/GithubAPI.o )

src/HolyProject/GithubAPI.hs:22:5: error:
    Variable not in scope:
      withManager :: (Manager -> m0 LZ.ByteString) -> IO LZ.ByteString
   |
22 |     withManager $ (return.responseBody) <=< httpLbs request
   |     ^^^^^^^^^^^
```

Here's how I reproduced the error locally:

```build
stack unpack holy-project-0.2.0.1 && cd holy-project-0.2.0.1
edit stack.yaml # add the following stack.yaml
stack build
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- http-conduit-2.3.0
```
